### ISSUE TITLE
Custom Resource does not have a delete logic

### ISSUE THREAD

**Issue by srirachanaachyuthuni** [awslabs/gaming-analytics-pipeline#3]
In  gaming-analytics-pipeline/source/custom-resource/custom_resource.py, the handler only handles create and not delete. This causes problems as users will not be able to delete the stack. Please modify this to check for event['RequestType'] = 'delete'.

**Comment by thomasphorton** [comment]
IIRC, the custom resource still handles 'Delete':

```
  if event['RequestType'] == 'Create':
    create(event, context)

  else:
    returnSuccess(event, context)
```

The underlying issue is that there is a dependency between the VPC and the Lambda, and on Delete the VPC Security Groups get removed before the Custom Resource can communicate back to CloudFormation, causing it to hang. I haven't been able to figure out a way to resolve this, so our guidance for now is to delete the stack through the console a second time after the first fails.

Thank you for reporting these issues!
